---
services:
  parse-dmarc:
    build: .
    image: ghcr.io/meysam81/parse-dmarc:latest
    ports:
      - "8080:8080"
    user: "1000:1000"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/data
